language: node_js

sudo: required

services:
  - docker

node_js:
  - "10"

before_install:
  - echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

install:
  - npm install

before_script:
  - npm test
  - npm run eslint

script:
  - ".travis/docker.sh"
  - ".travis/trigger-downstream.sh"

env:
  global:
    - DOCKER_USERNAME=mkroman
    - secure: "MaGrCvpBig4zt9UB7jqMVo0gb+SKNnnDBP0MqfDqSxnieFlCw5w8t64SQ/on5Aw/yGNtaZOpOi9FrUmQYmDZCJzvcNguz2P+Iw5RgvjYFPfEXTnzVRfEG3k6tZLld5sZsylWHNJxl2VlJfeWTzNRdoBMrh0zJsv3SrN5xAD+r1h33uXfPHCEJdrw5qEhY93F80AvYLZWVM2D9E6NPGdEl/voD5UC1RTbLdmRqs1GCl0xX9aTnK7+dleMqiaktNtGT3xjWjSRdZijQ0m6HydRQmZd7m6WksxI6ea/FJrfbIa6EPDE6yC5MAnK8Sgm11fhhSeSCbHb+QJhFfTO2RqGwqLWK6kVdF7wLIIMggGwk3diMkugKpY99Og8gAIKq1I0/hK78s2eURkcG5lccwbys4FpJcISPKPEGDC6jQmabEXJehi9RVTe1wtZ8Ay7xPKZnvv8SjO8K8VlII1o8mNWnMxm4uRYt2XxT9Pk5iqNLFNzXCwxA0b7sy2Hdubpr2qz2HvaHbXxhe1+JaunkBSLfFgsdGkKPS9NdUFR3ISLQvewged5oi+Q7wWocpskH15+tU1cWDZpoz1HpF1Sgtdh12K44XnJwz82/CLWSW/IiWgf6qZJwsBxnoOYEFu8oAXOHcYdK6lAYzhpluBE/04pP2lD09qOCJHpoEO4z+QMwb8="
